### ISSUE TITLE
Kiwisolver issue?

### ISSUE THREAD

**Issue by erobert98** [ayoung012/awslambda-matplotlib-layer#1]
Ive been trying to use kiwisovler since its a dependency in one of my scripts on aws lambda, im trying to use this idea, so i zipped the lib of the env i made, but im still unable to import module kiwisolver on lambda when i test my function. Ive addded the layer to the function as well. Seems to be because its written in a different language than what aws is expecting?

Any idea as to how to import kiwsolver on aws lambda?

**Comment by ayoung012** [comment]
No idea, sorry.
